server:
  port: 1314
spring:
  thymeleaf:
    cache: false
  application:
    name: NurseWeb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka