server:
  port: 1315
spring:
  thymeleaf:
    cache: false
  application:
    name: NurseWeb2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka