server:
  port: 10088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: XTL
    password: 15320721xzw12340
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: NurseProvider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info      
ProviderVersion: NurserProvider 8.8.8V
